version: "3.7"

services:
  server:
    build: .
    container_name: rust-graphql-example-server
    depends_on:
      - storage
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - POSTGRES_DB_HOST=storage
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - API_KEY=${API_KEY}
    ports:
      - ${PORT}:80
  storage:
    image: postgres:12.2
    container_name: rust-graphql-example-storage
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - storage-postgresql:/var/lib/postgresql/data

volumes:
  storage-postgresql:
    external:
      name: rust-graphql-example-storage
